[package]
name = "nostr-relays"
version = "0.0.1"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.13", features = ["derive"] }
env_logger = "0.10"
git2 = "0.19.0"
log = "0.4.24"
nostr-sdk = "0.19.1"
time = "0.1.39"
tokio = "1.26.0"
